FROM antinio/selenium_base:ubuntu24.04

# Копирование Chrome
COPY chrome-linux-arm64 /usr/local/chrome-linux-arm64
RUN ln -s /usr/local/chrome-linux-arm64/chrome /usr/bin/google-chrome

# Копирование Chromedriver
COPY chromedriver-linux-arm64/chromedriver /usr/bin/chromedriver
RUN chmod +x /usr/bin/chromedriver

# Настройка для Selenoid
CMD ["/usr/bin/chromedriver", "--port=4444", "--whitelisted-ips="]
